project:
  type: website
  output-dir: docs

website:
  title: "NS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - FinalProject.qmd
      - FinalProjectCode.qmd
      - Redesign.qmd
      - RedesignCode.qmd
      - Helpfulinfo.qmd
      - Resources.qmd
      
      
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    toc-location: left
    toc-title: "On this page"
    toc-depth: 4



